# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maria Inês Silva - Designer
email: mariainesssts@gmail.com
description:
  Maria Inês Silva - Designer
url: "http://yourdomain.com" # the base hostname & protocol for your site
keywords:
  Maria Inês Silva, Designer, Graphic Designer, HTML, CSS, JavaScript
exclude: [node_modules/]
